export class User {
    constructor(
        public _id : string,
        public firstName: string,
        public lastName: string,
        public email: string,
        public userName: string,
        public mailingAddress:string,
        public altMailingAddress:string,
        public phone:string,
        public altPhone:string,
        public ssn:string,
        public companyName:string,
        public gender:string,
        public password:string,
        public salary:string,
        public salaryTerm:string,
        public hireDate:string,
        public role:string,
        public mobileNumber:string,
        public skypeId:string,
        public dob:string,
        public facebook: string,
        public linkedin: string,
        public twitter: string,
        public github: string,
        public youtube: string,
        public createdAt:string,
        public updatedAt:string) { }
}